In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
dataset = pd.read_csv("gdrive/My Drive/Sleep_health_and_lifestyle_dataset.csv")
dataset

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,555,Female,43,Teacher,6.7,7,45,4,Overweight,135/90,65,6000,Insomnia
555,556,Male,43,Salesperson,6.5,6,45,7,Overweight,130/85,72,6000,Insomnia
556,557,Female,43,Teacher,6.7,7,45,4,Overweight,135/90,65,6000,Insomnia
557,558,Male,43,Salesperson,6.4,6,45,7,Overweight,130/85,72,6000,Insomnia
558,559,Male,43,Salesperson,6.5,6,45,7,Overweight,130/85,72,6000,Insomnia

In [ ]:
dataset['Sleep Disorder']=dataset['Sleep Disorder'].fillna("Healthy")

In [ ]:
dataset["Sleep Disorder"].value_counts()

Sleep Disorder
Healthy        375
Insomnia        93
Sleep Apnea     91
Name: count, dtype: int64

In [ ]:
!pip install imblearn

Requirement already satisfied: imblearn in /usr/local/lib/python3.12/dist-packages (0.0)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (from imblearn) (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (3.6.0)

In [ ]:
from imblearn.over_sampling import SMOTENC

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset.head(5)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,Healthy
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,Healthy
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,Healthy
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [ ]:
dataset['Systolic Pressure'] = dataset['Blood Pressure'].apply(lambda x: int(x.split('/')[0]))
dataset['Diastolic Pressure'] = dataset['Blood Pressure'].apply(lambda x: int(x.split('/')[1]))

In [ ]:
dataset.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Systolic Pressure,Diastolic Pressure
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,Healthy,126,83
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,Healthy,125,80
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,Healthy,125,80
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90

In [ ]:
dataset.drop('Blood Pressure',inplace=True,axis=1)
dataset.drop('Person ID',inplace=True,axis=1)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 559 entries, 0 to 558
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   559 non-null    object
 1   Age                      559 non-null    int64
 2   Occupation               559 non-null    object
 3   Sleep Duration           559 non-null    float64
 4   Quality of Sleep         559 non-null    int64
 5   Physical Activity Level  559 non-null    int64
 6   Stress Level             559 non-null    int64
 7   BMI Category             559 non-null    object
 8   Heart Rate               559 non-null    int64
 9   Daily Steps              559 non-null    int64
 10  Sleep Disorder           559 non-null    object
 11  Systolic Pressure        559 non-null    int64
 12  Diastolic Pressure       559 non-null    int64
dtypes: float64(1), int64(8), object(4)
memory usage: 56.9+ KB

In [ ]:
categorical_features = ['Gender','Occupation','BMI Category', 'Sleep Disorder']

In [ ]:
for cat in categorical_features:
  base = 0
  c_map = {}

  def map(x):
    global base

    if x in c_map.keys():
      return c_map[x]
    else:
      c_map[x] = base
      base+=1
      return c_map[x]

  dataset[cat] = dataset[cat].apply(map)

  print(cat," -> ",c_map)

Gender  ->  {'Male': 0, 'Female': 1}
Occupation  ->  {'Software Engineer': 0, 'Doctor': 1, 'Sales Representative': 2, 'Teacher': 3, 'Nurse': 4, 'Engineer': 5, 'Accountant': 6, 'Scientist': 7, 'Lawyer': 8, 'Salesperson': 9, 'Manager': 10}
BMI Category  ->  {'Overweight': 0, 'Normal': 1, 'Obese': 2, 'Normal Weight': 3}
Sleep Disorder  ->  {'Healthy': 0, 'Sleep Apnea': 1, 'Insomnia': 2}

In [ ]:
dataset.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic Pressure,Diastolic Pressure
0,0,27,0,6.1,6,42,6,0,77,4200,0,126,83
1,0,28,1,6.2,6,60,8,1,75,10000,0,125,80
2,0,28,1,6.2,6,60,8,1,75,10000,0,125,80
3,0,28,2,5.9,4,30,8,2,85,3000,1,140,90
4,0,28,2,5.9,4,30,8,2,85,3000,1,140,90

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 559 entries, 0 to 558
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   559 non-null    int64
 1   Age                      559 non-null    int64
 2   Occupation               559 non-null    int64
 3   Sleep Duration           559 non-null    float64
 4   Quality of Sleep         559 non-null    int64
 5   Physical Activity Level  559 non-null    int64
 6   Stress Level             559 non-null    int64
 7   BMI Category             559 non-null    int64
 8   Heart Rate               559 non-null    int64
 9   Daily Steps              559 non-null    int64
 10  Sleep Disorder           559 non-null    int64
 11  Systolic Pressure        559 non-null    int64
 12  Diastolic Pressure       559 non-null    int64
dtypes: float64(1), int64(12)
memory usage: 56.9 KB

In [ ]:
categorical_features = [0, 2, 7, 10]

print("Categorical feature indices:", categorical_features)

Categorical feature indices: [0, 2, 7, 10]

0  → Gender

2  → Occupation

7  → BMI Category

10 → Sleep Disorder

In [ ]:
X = dataset.drop('Sleep Disorder', axis=1)
y = dataset['Sleep Disorder']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (559, 12)
y shape: (559,)

In [ ]:
print(y.value_counts())

Sleep Disorder
0    375
2     93
1     91
Name: count, dtype: int64

0 → Healthy → 375

1 → Sleep Apnea → 93

2 → Insomnia → 91

In [ ]:
target_total = 1500

healthy = round(375 / 559 * target_total)
sleep_apnea = round(91 / 559 * target_total)
insomnia = target_total - healthy - sleep_apnea

print("Healthy:", healthy)
print("Sleep Apnea:", sleep_apnea)
print("Insomnia:", insomnia)
print("Total:", healthy + sleep_apnea + insomnia)

Healthy: 1006
Sleep Apnea: 244
Insomnia: 250
Total: 1500

In [ ]:
sampling_strategy = {
    0: 1006,
    1: 244,
    2: 250
}

In [ ]:
categorical_features = [0, 2, 7]

In [ ]:
from imblearn.over_sampling import SMOTENC

smotenc = SMOTENC(
    categorical_features=categorical_features,
    random_state=42,
    sampling_strategy=sampling_strategy
)

In [ ]:
X_resampled, y_resampled = smotenc.fit_resample(X, y)

In [ ]:
print("X shape:", X_resampled.shape)
print("y shape:", y_resampled.shape)

print(y_resampled.value_counts())

X shape: (1500, 13)
y shape: (1500,)
Sleep Disorder
0    1006
2     250
1     244
Name: count, dtype: int64

In [ ]:
new_dataset = pd.DataFrame(X_resampled, columns=X.columns)

new_dataset['Sleep Disorder'] = y_resampled

print(new_dataset.shape)
new_dataset.head()

(1500, 13)

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Systolic Pressure,Diastolic Pressure,Sleep Disorder
0,0,27,0,6.1,6,42,6,0,77,4200,126,83,0
1,0,28,1,6.2,6,60,8,1,75,10000,125,80,0
2,0,28,1,6.2,6,60,8,1,75,10000,125,80,0
3,0,28,2,5.9,4,30,8,2,85,3000,140,90,1
4,0,28,2,5.9,4,30,8,2,85,3000,140,90,1

In [ ]:
new_dataset.insert(0, 'Person ID', range(1, len(new_dataset) + 1))

In [ ]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                1500 non-null   int64
 1   Gender                   1500 non-null   int64
 2   Age                      1500 non-null   int64
 3   Occupation               1500 non-null   int64
 4   Sleep Duration           1500 non-null   float64
 5   Quality of Sleep         1500 non-null   int64
 6   Physical Activity Level  1500 non-null   int64
 7   Stress Level             1500 non-null   int64
 8   BMI Category             1500 non-null   int64
 9   Heart Rate               1500 non-null   int64
 10  Daily Steps              1500 non-null   int64
 11  Systolic Pressure        1500 non-null   int64
 12  Diastolic Pressure       1500 non-null   int64
 13  Sleep Disorder           1500 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 164.2 KB

In [ ]:
print("Missing values:")
print(new_dataset.isnull().sum())

Missing values:
Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Heart Rate                 0
Daily Steps                0
Systolic Pressure          0
Diastolic Pressure         0
Sleep Disorder             0
dtype: int64

In [ ]:
print("Duplicate rows:", new_dataset.duplicated().sum())

Duplicate rows: 0

In [ ]:
print(new_dataset.describe())

         Person ID       Gender          Age  Occupation  Sleep Duration  \
count  1500.000000  1500.000000  1500.000000  1500.00000     1500.000000
mean    750.500000     0.428667    40.185333     4.65600        7.138764
std     433.157015     0.495050     8.077860     2.69094        0.730920
min       1.000000     0.000000    27.000000     0.00000        5.800000
25%     375.750000     0.000000    33.000000     3.00000        6.500000
50%     750.500000     0.000000    39.000000     5.00000        7.200000
75%    1125.250000     1.000000    44.000000     7.00000        7.700000
max    1500.000000     1.000000    59.000000    10.00000        8.500000

       Quality of Sleep  Physical Activity Level  Stress Level  BMI Category  \
count       1500.000000              1500.000000   1500.000000   1500.000000
mean           7.266000                59.015333      5.384000      0.857333
std            1.136708                19.698370      1.653996      0.767706
min            4.000000                30.000000      3.000000      0.000000
25%            6.000000                45.000000      4.000000      0.000000
50%            7.000000                60.000000      5.000000      1.000000
75%            8.000000                75.000000      7.000000      1.000000
max            9.000000                90.000000      8.000000      3.000000

        Heart Rate   Daily Steps  Systolic Pressure  Diastolic Pressure  \
count  1500.000000   1500.000000        1500.000000         1500.000000
mean     70.196667   6817.136667         126.925333           83.440667
std       3.848445   1523.586064           7.462767            5.670619
min      65.000000   3000.000000         115.000000           75.000000
25%      68.000000   5500.000000         120.000000           80.000000
50%      70.000000   7000.000000         128.000000           84.000000
75%      72.000000   8000.000000         130.000000           85.000000
max      86.000000  10000.000000         142.000000           95.000000

       Sleep Disorder
count     1500.000000
mean         0.496000
std          0.764007
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          2.000000

Gender  ->  {'Male': 0, 'Female': 1}

Occupation  ->  {'Software Engineer': 0, 'Doctor': 1, 'Sales Representative': 2, 'Teacher': 3, 'Nurse': 4, 'Engineer': 5, 'Accountant': 6, 'Scientist': 7, 'Lawyer': 8, 'Salesperson': 9, 'Manager': 10}

BMI Category  ->  {'Overweight': 0, 'Normal': 1, 'Obese': 2, 'Normal Weight': 3}

Sleep Disorder  ->  {'Healthy': 0, 'Sleep Apnea': 1, 'Insomnia': 2}

In [ ]:
gender_map = {
    0: 'Male',
    1: 'Female'
}

occupation_map = {
    0: 'Software Engineer',
    1: 'Doctor',
    2: 'Sales Representative',
    3: 'Teacher',
    4: 'Nurse',
    5: 'Engineer',
    6: 'Accountant',
    7: 'Scientist',
    8: 'Lawyer',
    9: 'Salesperson',
    10: 'Manager'
}

bmi_map = {
    0: 'Overweight',
    1: 'Normal',
    2: 'Obese',
    3: 'Normal Weight'
}

sleep_map = {
    0: 'Healthy',
    1: 'Sleep Apnea',
    2: 'Insomnia'
}

In [ ]:
new_dataset['Gender'] = new_dataset['Gender'].map(gender_map)

new_dataset['Occupation'] = new_dataset['Occupation'].map(occupation_map)

new_dataset['BMI Category'] = new_dataset['BMI Category'].map(bmi_map)

new_dataset['Sleep Disorder'] = new_dataset['Sleep Disorder'].map(sleep_map)

In [ ]:
print(new_dataset.head())

   Person ID Gender  Age            Occupation  Sleep Duration  \
0          1   Male   27     Software Engineer             6.1
1          2   Male   28                Doctor             6.2
2          3   Male   28                Doctor             6.2
3          4   Male   28  Sales Representative             5.9
4          5   Male   28  Sales Representative             5.9

   Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                 6                       42             6   Overweight
1                 6                       60             8       Normal
2                 6                       60             8       Normal
3                 4                       30             8        Obese
4                 4                       30             8        Obese

   Heart Rate  Daily Steps  Systolic Pressure  Diastolic Pressure  \
0          77         4200                126                  83
1          75        10000                125                  80
2          75        10000                125                  80
3          85         3000                140                  90
4          85         3000                140                  90

  Sleep Disorder
0        Healthy
1        Healthy
2        Healthy
3    Sleep Apnea
4    Sleep Apnea

In [ ]:
print("Missing values:")
print(new_dataset.isnull().sum())

In [ ]:
print("Data types:")
print(new_dataset.dtypes)

In [ ]:
print("Shape:", new_dataset.shape)

Shape: (1500, 14)

In [ ]:
new_dataset['Blood Pressure'] = (
    new_dataset['Systolic Pressure'].astype(str)
    + '/'
    + new_dataset['Diastolic Pressure'].astype(str)
)

In [ ]:
new_dataset.drop(
    ['Systolic Pressure', 'Diastolic Pressure'],
    axis=1,
    inplace=True
)

In [ ]:
new_dataset.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Blood Pressure
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,Healthy,126/83
1,2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,Healthy,125/80
2,3,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,Healthy,125/80
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140/90
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140/90

In [ ]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                1500 non-null   int64
 1   Gender                   1500 non-null   object
 2   Age                      1500 non-null   int64
 3   Occupation               1500 non-null   object
 4   Sleep Duration           1500 non-null   float64
 5   Quality of Sleep         1500 non-null   int64
 6   Physical Activity Level  1500 non-null   int64
 7   Stress Level             1500 non-null   int64
 8   BMI Category             1500 non-null   object
 9   Heart Rate               1500 non-null   int64
 10  Daily Steps              1500 non-null   int64
 11  Sleep Disorder           1500 non-null   object
 12  Blood Pressure           1500 non-null   object
dtypes: float64(1), int64(7), object(5)
memory usage: 152.5+ KB

In [ ]:
new_dataset.to_csv("SMOTENC_1500_Synthetic_Dataset.csv", index=False)

In [ ]:
import os

print(os.path.exists("SMOTENC_1500_Synthetic_Dataset.csv"))

True

In [ ]:
from google.colab import files

files.download("SMOTENC_1500_Synthetic_Dataset.csv")